### ISSUE TITLE
which ubuntu is better?

### ISSUE THREAD

**Issue by WMJi** [UBTC/IIMW#1]
Kubuntu is not stable.
Xubuntu is buggy and is not fixed in time.
Mubuntu's compatibility is still kind of limited.
Gubuntu is not that flexible, but may be the best choice nowadays.
Ubuntu is yet another good choice, although it is not as robust as Gubuntu.

**Comment by MogeiWang** [comment]
hotkeys:
W-z : max window
W-S-z : min window
W-x : launcher
W-S-X : move window
W-c : window menu
W-S-c : close window

**Comment by MogeiWang** [comment]
Always install [Gubuntu](https://ubuntugnome.org/download/), 
unless the unity GUI gets really (very?) competitive.

**Comment by MogeiWang** [comment]
[kubuntu](http://www.kubuntu.org/) is also VERY good!
It was not so stable, but currently, it seems just fine!

**Comment by MogeiWang** [comment]
[Xubuntu](http://xubuntu.org/getxubuntu/) still wins in stability and flexibility.

**Comment by MogeiWang** [comment]
Kubuntu is not stable.
Xubuntu is buggy and is not fixed in time.
Gubuntu is not that flexible, but it is the best choice till now.

**Comment by MogeiWang** [comment]
Are mate
```
    sudo apt-get install ubuntu-mate-desktop
```

and cinnamon
```
    sudo add-apt-repository ppa:embrosyn/cinnamon
    sudo apt-get update
    sudo apt-get install cinnamon cinnamon-core 
````

better choices?

**Comment by MogeiWang** [comment]
[Mububtu](https://ubuntu-mate.org/download/) may be the best one?

**Comment by MogeiWang** [comment]
Gonme3 wins mate and cinnamon in 2 aspects,
1) it is more much unified, and
2) it is better completed.

So, why bother? Just use Gubuntu.

**Comment by MogeiWang** [comment]
Finnal choice: Mubuntu and Gubuntu.

Mubuntu is more flexible, while Gubuntu may has better compatibility.
Try Mubuntu first, since it is simpler and has a better logo.

**Comment by MaojiWang** [comment]
Mate may be the best desktop so far.
Although, it did not work well with the HP printer (Gnome worked fine)...

**Comment by wmji** [comment]
Installed Mate 1.18 on Ubuntu 16.04 (following [this tip](http://tipsonubuntu.com/2017/03/15/install-mate-desktop-1-18-in-ubuntu-16-04/))

so far so good.

Although the HP printing has not been tested yet.

**Comment by wmji** [comment]
Try Lubuntu?

**Comment by WMJi** [comment]
switching to Xubuntu.

The next Ubuntu will ship Gnome-desktop, which sounds promising.
But I cannot wait that long.
Also, they are resource consuming.

Mubuntu is a bit dated and complicated.

**Comment by WMJi** [comment]
how about [lxqt](https://github.com/lxde/lxqt/)?

```
sudo add-apt-repository -y ppa:lubuntu-dev/lubuntu-daily
sudo apt-get update

sudo apt-get install pcmanfm-qt lxqt-admin lxqt-common lxqt-config lxqt-globalkeys lxqt-notificationd lxqt-panel lxqt-policykit lxqt-powermanagement lxqt-qtplugin lxqt-runner lxqt-session lxqt-sudo

sudo apt-get --no-install-recommends install kwin kwin-style-breeze kwin-addons systemsettings kde-style-breeze kde-style-breeze-qt4  breeze breeze-cursor-theme breeze-icon-theme

sudo update-alternatives --config x-session-manager
```
